### ISSUE TITLE
Tabs misses top-margin

### ISSUE THREAD

**Issue by RomainLanz** [apex/apex-ui-slim#6]
Hey!

After installer `apex-ui-slim` and `no-title-bar` my tab doesn't have any top-margin.

**Example:**
<img width="614" alt="screen shot 2017-01-13 at 16 33 41" src="https://cloud.githubusercontent.com/assets/2793951/21935534/3603589e-d9ae-11e6-9310-6232b2690a4c.png">

How to fix that?

**Comment by kocisov** [comment]
You can fix that with
```css
.tab-bar .tab {
  margin-top: 10px;
}
```

**Comment by RomainLanz** [comment]
Thanks!
